apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-reader
  namespace: relativa
  labels:
    app.kubernetes.io/name: migration-reader
    app.kubernetes.io/part-of: relativa
    app.kubernetes.io/component: migration
