apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: relativa
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: relativa
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
