apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: relativa
  labels:
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: relativa
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: relativa
  ports:
    - name: http
      port: 8082
      targetPort: http
