apiVersion: v1
kind: Service
metadata:
  name: ml
  namespace: relativa
  labels:
    app.kubernetes.io/name: ml
    app.kubernetes.io/part-of: relativa
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ml
    app.kubernetes.io/part-of: relativa
  ports:
    - name: http
      port: 8084
      targetPort: http
