image:
  tag: 1.1.0
  pullPolicy: IfNotPresent

config:
  aspnetcoreEnvironment: Development

ingress:
  enabled: false

postgres:
  persistence:
    size: 1Gi

auth:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 384Mi

audit:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 384Mi

ml:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      cpu: "1"
      memory: 1Gi

gateway:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

client:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
