// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Relativa.Migration.Data;

#nullable disable

namespace Relativa.Migration.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    partial class MigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditLogs.EntityAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedById")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FieldName")
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<JsonDocument>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<JsonDocument>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_entity_audit_log_changed_at");

                    b.HasIndex("ChangedById", "ChangedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_eal_changed_by_changed_at");

                    b.HasIndex("EntityId", "ChangedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_eal_entity_changed_at");

                    b.ToTable("entity_audit_log", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditLogs.OrganizationAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedById")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldName")
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<JsonDocument>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<JsonDocument>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_organization_audit_log_changed_at");

                    b.HasIndex("ChangedById", "ChangedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_oal_changed_by_changed_at");

                    b.HasIndex("OrganizationId", "ChangedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_oal_organization_changed_at");

                    b.ToTable("organization_audit_log", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditLogs.UserAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedById")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldName")
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<JsonDocument>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<JsonDocument>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_user_audit_log_changed_at");

                    b.HasIndex("ChangedById", "ChangedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ual_changed_by_changed_at");

                    b.HasIndex("TargetUserId", "ChangedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ual_target_user_changed_at");

                    b.ToTable("user_audit_log", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditLogs.WorkspaceAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedById")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldName")
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<JsonDocument>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<JsonDocument>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<int?>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_workspace_audit_log_changed_at");

                    b.HasIndex("ChangedById", "ChangedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_wal_changed_by_changed_at");

                    b.HasIndex("WorkspaceId", "ChangedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_wal_workspace_changed_at");

                    b.ToTable("workspace_audit_log", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("publish_attempts");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("routing_key");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_audit_outbox_created_at_utc");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_outbox_event_id");

                    b.HasIndex("PublishedAtUtc", "Id")
                        .HasDatabaseName("ix_audit_outbox_pending");

                    b.ToTable("audit_outbox", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("EventId");

                    b.ToTable("audit_processed_event", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_entity_created_by_user");

                    b.HasIndex("EntityTypeId");

                    b.ToTable("entity", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityPropertyValue", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.Property<decimal?>("ValueDecimal")
                        .HasColumnType("numeric")
                        .HasColumnName("value_decimal");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("integer")
                        .HasColumnName("value_int");

                    b.Property<string>("ValueString")
                        .HasColumnType("text")
                        .HasColumnName("value_string");

                    b.HasKey("EntityId", "PropertyId");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_epv_property_id");

                    b.ToTable("entity_property_value", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RelationshipTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type_id");

                    b.Property<int>("SourceEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("source_entity_id");

                    b.Property<int>("TargetEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("target_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipTypeId")
                        .HasDatabaseName("ix_er_relationship_type_id");

                    b.HasIndex("SourceEntityId")
                        .HasDatabaseName("ix_er_source_entity_id");

                    b.HasIndex("TargetEntityId")
                        .HasDatabaseName("ix_er_target_entity_id");

                    b.HasIndex("SourceEntityId", "RelationshipTypeId", "TargetEntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_er_source_type_target_unique");

                    b.ToTable("entity_relationship", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityRelationshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RelationshipCardinality")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("relationship_cardinality");

                    b.Property<int>("SourceEntityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("source_entity_type_id");

                    b.Property<int>("TargetEntityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("target_entity_type_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_entity_relationship_type_name");

                    b.HasIndex("SourceEntityTypeId");

                    b.HasIndex("TargetEntityTypeId");

                    b.ToTable("entity_relationship_type", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsStandalone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_standalone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_entity_type_name");

                    b.ToTable("entity_type", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityTypeProperty", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type_id");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.HasKey("EntityTypeId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("entity_type_property", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityWorkspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_ew_workspace_id");

                    b.HasIndex("EntityId", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_ew_entity_workspace");

                    b.ToTable("entity_workspace", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("invited_by_user_id");

                    b.Property<int>("OrgRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("org_role_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("OrgRoleId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_org_invitations_token");

                    b.HasIndex("Email", "Status")
                        .HasDatabaseName("ix_oi_email_status");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_oi_org_status");

                    b.ToTable("organization_invitations", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationJoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_ojr_org_status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_ojr_user_status");

                    b.ToTable("organization_join_requests", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Name", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_org_roles_name_org");

                    b.ToTable("organization_roles", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrgRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("org_role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgRoleId");

                    b.HasIndex("PermissionId");

                    b.ToTable("organization_role_permissions", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefaultOrgRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("default_org_role_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("JoinPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasDefaultValue("open")
                        .HasColumnName("join_policy");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("DefaultOrgRoleId");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_org_settings_organization_id");

                    b.ToTable("organization_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_org_settings_join_policy", "join_policy IN ('open', 'invite_only')");
                        });
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsReadonly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readonly");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("property", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.PropertyAllowedValue", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.HasKey("PropertyId", "Value");

                    b.ToTable("property_allowed_value", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.RabbitMqProcessedDelivery", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("ConsumerGroup")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("consumer_group");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("MessageId", "ConsumerGroup");

                    b.ToTable("rabbitmq_processed_delivery", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_token_expires_at");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorMasterCodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("two_factor_master_code_hash");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("two_factor_secret");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"is_archived\" = FALSE");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserBackupCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_backup_codes_user_id");

                    b.ToTable("user_backup_codes", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("verification_token");

                    b.Property<DateTime?>("VerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_token_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("ix_user_emails_address");

                    b.HasIndex("UserId");

                    b.ToTable("user_emails", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserExternalLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_user_external_logins_provider_subject");

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserRoleOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("OrgRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("org_role_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgRoleId");

                    b.HasIndex("OrganizationId", "IsArchived")
                        .HasDatabaseName("ix_uro_org_active");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_org_user_org");

                    b.ToTable("user_role_organization", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserRoleWorkspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.Property<int>("WsRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("ws_role_id");

                    b.HasKey("Id");

                    b.HasIndex("WsRoleId");

                    b.HasIndex("UserId", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_workspace_user_ws");

                    b.HasIndex("WorkspaceId", "IsArchived")
                        .HasDatabaseName("ix_urw_workspace_active");

                    b.ToTable("user_role_workspace", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en")
                        .HasColumnName("locale");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_settings_user_id");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.WorkspaceRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int?>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("Name", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_roles_name_workspace");

                    b.ToTable("workspace_roles", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.WorkspaceRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<int>("WsRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("ws_role_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("WsRoleId");

                    b.ToTable("workspace_role_permissions", (string)null);
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.WorkspaceSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("HighRiskThreshold")
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.7m)
                        .HasColumnName("high_risk_threshold");

                    b.Property<decimal>("MediumRiskThreshold")
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.4m)
                        .HasColumnName("medium_risk_threshold");

                    b.Property<bool>("RiskScoringEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("risk_scoring_enabled");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_settings_workspace_id");

                    b.ToTable("workspace_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_settings_high_risk", "high_risk_threshold BETWEEN 0.00 AND 1.00");

                            t.HasCheckConstraint("ck_workspace_settings_medium_risk", "medium_risk_threshold BETWEEN 0.00 AND 1.00 AND medium_risk_threshold < high_risk_threshold");
                        });
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditLogs.EntityAuditLog", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_entity_audit_log_users");

                    b.HasOne("Relativa.Persistence.Entities.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_entity_audit_log_entities");

                    b.Navigation("ChangedBy");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditLogs.OrganizationAuditLog", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_organization_audit_log_users");

                    b.HasOne("Relativa.Persistence.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_organization_audit_log_organizations");

                    b.Navigation("ChangedBy");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditLogs.UserAuditLog", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_audit_log_users");

                    b.HasOne("Relativa.Persistence.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_audit_log_target_users");

                    b.Navigation("ChangedBy");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.AuditLogs.WorkspaceAuditLog", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workspace_audit_log_users");

                    b.HasOne("Relativa.Persistence.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workspace_audit_log_workspaces");

                    b.Navigation("ChangedBy");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Entity", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "CreatedByUser")
                        .WithMany("CreatedEntities")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_created_by_user");

                    b.HasOne("Relativa.Persistence.Entities.EntityType", "EntityType")
                        .WithMany("Entities")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_entity_type");

                    b.Navigation("CreatedByUser");

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityPropertyValue", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.Entity", "Entity")
                        .WithMany("EntityPropertyValues")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epv_entity");

                    b.HasOne("Relativa.Persistence.Entities.Property", "Property")
                        .WithMany("EntityPropertyValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epv_property");

                    b.Navigation("Entity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityRelationship", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.EntityRelationshipType", "RelationshipType")
                        .WithMany("EntityRelationships")
                        .HasForeignKey("RelationshipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_er_relationship_type");

                    b.HasOne("Relativa.Persistence.Entities.Entity", "SourceEntity")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("SourceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_er_source_entity");

                    b.HasOne("Relativa.Persistence.Entities.Entity", "TargetEntity")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_er_target_entity");

                    b.Navigation("RelationshipType");

                    b.Navigation("SourceEntity");

                    b.Navigation("TargetEntity");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityRelationshipType", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.EntityType", "SourceEntityType")
                        .WithMany("SourceRelationshipTypes")
                        .HasForeignKey("SourceEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ert_source_entity_type");

                    b.HasOne("Relativa.Persistence.Entities.EntityType", "TargetEntityType")
                        .WithMany("TargetRelationshipTypes")
                        .HasForeignKey("TargetEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ert_target_entity_type");

                    b.Navigation("SourceEntityType");

                    b.Navigation("TargetEntityType");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityTypeProperty", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.EntityType", "EntityType")
                        .WithMany("EntityTypeProperties")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etp_entity_type");

                    b.HasOne("Relativa.Persistence.Entities.Property", "Property")
                        .WithMany("EntityTypeProperties")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etp_property");

                    b.Navigation("EntityType");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityWorkspace", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.Entity", "Entity")
                        .WithMany("EntityWorkspaces")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ew_entity");

                    b.HasOne("Relativa.Persistence.Entities.Workspace", "Workspace")
                        .WithMany("EntityWorkspaces")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ew_workspace");

                    b.Navigation("Entity");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationInvitation", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_oi_invited_by");

                    b.HasOne("Relativa.Persistence.Entities.OrganizationRole", "Role")
                        .WithMany()
                        .HasForeignKey("OrgRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_oi_org_role");

                    b.HasOne("Relativa.Persistence.Entities.Organization", "Organization")
                        .WithMany("Invitations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oi_organization");

                    b.Navigation("InvitedBy");

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationJoinRequest", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.Organization", "Organization")
                        .WithMany("JoinRequests")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ojr_organization");

                    b.HasOne("Relativa.Persistence.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ojr_reviewed_by");

                    b.HasOne("Relativa.Persistence.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ojr_user");

                    b.Navigation("Organization");

                    b.Navigation("ReviewedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationRole", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_org_roles_organization");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationRolePermission", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.OrganizationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("OrgRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orp_role");

                    b.HasOne("Relativa.Persistence.Entities.Permission", "Permission")
                        .WithMany("OrganizationRolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orp_permission");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationSettings", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.OrganizationRole", "DefaultOrgRole")
                        .WithMany()
                        .HasForeignKey("DefaultOrgRoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_org_settings_default_org_role");

                    b.HasOne("Relativa.Persistence.Entities.Organization", "Organization")
                        .WithOne("Settings")
                        .HasForeignKey("Relativa.Persistence.Entities.OrganizationSettings", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_settings_organization");

                    b.Navigation("DefaultOrgRole");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Property", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_property_organization");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.PropertyAllowedValue", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.Property", "Property")
                        .WithMany("AllowedValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_allowed_value_property");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserBackupCode", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "User")
                        .WithMany("BackupCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_backup_codes_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserEmail", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "User")
                        .WithMany("Emails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_emails_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_external_logins_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserRoleOrganization", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.OrganizationRole", "Role")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("OrgRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_uro_role");

                    b.HasOne("Relativa.Persistence.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uro_organization");

                    b.HasOne("Relativa.Persistence.Entities.User", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uro_user");

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserRoleWorkspace", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_urw_user");

                    b.HasOne("Relativa.Persistence.Entities.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_urw_workspace");

                    b.HasOne("Relativa.Persistence.Entities.WorkspaceRole", "Role")
                        .WithMany("WorkspaceMembers")
                        .HasForeignKey("WsRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_urw_role");

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.UserSettings", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("Relativa.Persistence.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Workspace", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_created_by");

                    b.HasOne("Relativa.Persistence.Entities.Organization", "Organization")
                        .WithMany("Workspaces")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_organization");

                    b.Navigation("CreatedBy");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.WorkspaceRole", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.Workspace", "Workspace")
                        .WithMany("Roles")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_ws_roles_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.WorkspaceRolePermission", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.Permission", "Permission")
                        .WithMany("WorkspaceRolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wsrp_permission");

                    b.HasOne("Relativa.Persistence.Entities.WorkspaceRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("WsRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wsrp_role");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.WorkspaceSettings", b =>
                {
                    b.HasOne("Relativa.Persistence.Entities.Workspace", "Workspace")
                        .WithOne("WorkspaceSettings")
                        .HasForeignKey("Relativa.Persistence.Entities.WorkspaceSettings", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_settings_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Entity", b =>
                {
                    b.Navigation("EntityPropertyValues");

                    b.Navigation("EntityWorkspaces");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityRelationshipType", b =>
                {
                    b.Navigation("EntityRelationships");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.EntityType", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("EntityTypeProperties");

                    b.Navigation("SourceRelationshipTypes");

                    b.Navigation("TargetRelationshipTypes");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Organization", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("JoinRequests");

                    b.Navigation("Members");

                    b.Navigation("Roles");

                    b.Navigation("Settings");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.OrganizationRole", b =>
                {
                    b.Navigation("OrganizationMembers");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Permission", b =>
                {
                    b.Navigation("OrganizationRolePermissions");

                    b.Navigation("WorkspaceRolePermissions");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Property", b =>
                {
                    b.Navigation("AllowedValues");

                    b.Navigation("EntityPropertyValues");

                    b.Navigation("EntityTypeProperties");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.User", b =>
                {
                    b.Navigation("BackupCodes");

                    b.Navigation("CreatedEntities");

                    b.Navigation("Emails");

                    b.Navigation("ExternalLogins");

                    b.Navigation("OrganizationMemberships");

                    b.Navigation("Settings");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.Workspace", b =>
                {
                    b.Navigation("EntityWorkspaces");

                    b.Navigation("Members");

                    b.Navigation("Roles");

                    b.Navigation("WorkspaceSettings");
                });

            modelBuilder.Entity("Relativa.Persistence.Entities.WorkspaceRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("WorkspaceMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
