{{- define "relativa.auth.env" -}}
{{ include "relativa.configEnv" (dict "root" . "name" "ASPNETCORE_ENVIRONMENT") }}
{{ include "relativa.databaseEnv" (dict "root" .) }}
{{ include "relativa.jwtEnv" (dict "root" .) }}
{{ include "relativa.rabbitmqEnv" (dict "root" . "sections" (list "RabbitMqAudit")) }}
{{ include "relativa.configEnv" (dict "root" . "name" "Smtp__Host" "key" "SMTP_HOST") }}
{{ include "relativa.configEnv" (dict "root" . "name" "Smtp__Port" "key" "SMTP_PORT") }}
{{ include "relativa.configEnv" (dict "root" . "name" "App__FrontendBaseUrl" "key" "CLIENT_PUBLIC_URL") }}
{{- end }}
{{ include "relativa.appDeployment" (dict "root" . "component" "auth" "waitForDependencies" true "waitForMigration" true "env" (include "relativa.auth.env" .)) }}
