{{- define "relativa.core.env" -}}
{{ include "relativa.configEnv" (dict "root" . "name" "ASPNETCORE_ENVIRONMENT") }}
{{ include "relativa.databaseEnv" (dict "root" .) }}
{{ include "relativa.rabbitmqEnv" (dict "root" . "sections" (list "RabbitMqAudit" "RabbitMqGraph")) }}
{{- end }}
{{ include "relativa.appDeployment" (dict "root" . "component" "core" "waitForDependencies" true "env" (include "relativa.core.env" .)) }}
