{{- define "relativa.graph.env" -}}
{{ include "relativa.configEnv" (dict "root" . "name" "ASPNETCORE_ENVIRONMENT") }}
{{ include "relativa.databaseEnv" (dict "root" .) }}
{{ include "relativa.rabbitmqEnv" (dict "root" . "sections" (list "RabbitMqGraph")) }}
{{ include "relativa.configEnv" (dict "root" . "name" "MlApi__BaseUrl" "key" "ML_URL") }}
{{- end }}
{{ include "relativa.appDeployment" (dict "root" . "component" "graph" "waitForDependencies" true "waitForMigration" true "env" (include "relativa.graph.env" .)) }}
