apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relativa.migrationReaderName" . }}
  labels:
    {{- include "relativa.labels" (dict "root" . "component" "migration-reader") | nindent 4 }}
