{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "relativa.componentName" (dict "root" . "component" "postgres") }}
  labels:
    {{- include "relativa.labels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.postgres.persistence.accessModes | nindent 4 }}
  {{- with .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ include "relativa.claimSize" (dict "root" . "name" (include "relativa.componentName" (dict "root" . "component" "postgres")) "size" .Values.postgres.persistence.size) }}
{{- end }}
