apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relativa.secretName" . }}
  labels:
    {{- include "relativa.labels" (dict "root" .) | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ required "secrets.dbPassword is required" .Values.secrets.dbPassword | quote }}
  RABBITMQ_PASSWORD: {{ required "secrets.rabbitmqPassword is required" .Values.secrets.rabbitmqPassword | quote }}
  JWT_SECRET_KEY: {{ required "secrets.jwtSecretKey is required" .Values.secrets.jwtSecretKey | quote }}
